project_id = "sqpiuquzcejtyuqykvxn"

[functions.prompt-engine]
verify_jwt = false

[functions.prompt-engine-creative]  
verify_jwt = false

[functions.prompt-engine-communication]
verify_jwt = false

[functions.prompt-engine-strategic]
verify_jwt = false

[functions.prompt-engine-consolidated]
verify_jwt = false

[functions.chat-router]
verify_jwt = true

[functions.model-gateway]
verify_jwt = true

[functions.websearch-edge]
verify_jwt = true

[functions.news-feeds-edge]
verify_jwt = true